cleanup

diff --git a/process/folderput b/process/folderput
--- a/process/folderput
+++ b/process/folderput
@@ -2,16 +2,38 @@
 
 set -e
 
-USAGE="Usage: folderput [path] [db] [child_folder_id]"
+usage()
+{
+  echo "Usage: folderput -d [db_name] -c [child_folder_id] path"
+}
 
-if [ $# -lt 2 ]; then
-  echo "$USAGE"
+while getopts ":d:c:" opt; do
+  case $opt in
+    d)
+      DB_NAME=$OPTARG
+      ;;
+    c)
+      CHILD_FOLDER_ID=$OPTARG
+      ;;
+    \?)
+      echo "Invalid option: -$OPTARG" >&2
+      exit 1
+      ;;
+    :)
+      echo "Option -$OPTARG requires an argument." >&2
+      exit 1
+      ;;
+  esac
+done
+
+if [ -z "$DB_NAME" ]; then
+  usage
   exit 1
 fi
 
+shift $((OPTIND-1))
+
 FOLDER_PATH=$1
-DB_NAME=$2
-CHILD_FOLDER_ID=$3
 
 [ "$MONGO_HOST" = "" ] && MONGO_HOST="127.0.0.1:27017"
 MONGO_DB="$DB_NAME"
@@ -28,11 +50,12 @@ if [ "$CHILD_FOLDER_ID" != "" ]; then
   mongo --quiet $MONGO_HOST/$MONGO_DB --eval "db.$MONGO_COLLECTION_FOLDER.update( { _id: $FOLDER_ID, children: { \$not: { \$in: [ $CHILD_FOLDER_ID ] } } }, { \$push: { children: $CHILD_FOLDER_ID } } )" >/dev/null
 fi
 
+# handle parent
 if [ "$FOLDER_PATH" != "" ]; then
   PARENT_FOLDER_PATH=$(dirname "$FOLDER_PATH")
   [ "$PARENT_FOLDER_PATH" = "." ] && PARENT_FOLDER_PATH=""
 
-  ./folderput "$PARENT_FOLDER_PATH" "$MONGO_DB" $FOLDER_ID
+  ./folderput -d "$MONGO_DB" -c "$FOLDER_ID" "$PARENT_FOLDER_PATH"
 fi
 
 [ "$CHILD_FOLDER_ID" = "" ] && echo "$FOLDER_ID"
diff --git a/process/resourceput b/process/resourceput
--- a/process/resourceput
+++ b/process/resourceput
@@ -1,17 +1,41 @@
 #!/bin/bash
 
 set -e
-#set -x
 
-USAGE="Usage: resourceput [resource_key] [db_name]"
+usage()
+{
+  echo "Usage: resourceput -d [db_name] [resource_key]" 
+}
 
-if [ $# -ne 2 ]; then
-  echo "$USAGE"
+while getopts ":d:" opt; do
+  case $opt in
+    d)
+      DB_NAME=$OPTARG
+      ;;
+    \?)
+      echo "Invalid option: -$OPTARG" >&2
+      exit 1
+      ;;
+    :)
+      echo "Option -$OPTARG requires an argument." >&2
+      exit 1
+      ;;
+  esac
+done
+
+if [ -z "$DB_NAME" ]; then
+  usage
   exit 1
 fi
 
+shift $((OPTIND-1))
+
 RESOURCE_KEY=$1
-DB_NAME=$2
+
+if [ -z "$RESOURCE_KEY" ]; then
+  usage
+  exit 1
+fi
 
 RESOURCE_NAME=$(basename "$RESOURCE_KEY")
 
@@ -21,7 +45,10 @@ MONGO_COLLECTION_RESOURCE=resource
 
 # lookup folder_id
 FOLDER_KEY=$(dirname "$RESOURCE_KEY")
-FOLDER_ID=$(./folderput "$FOLDER_KEY" "$DB_NAME")
+
+[ "$FOLDER_KEY" = "." ] && FOLDER_KEY=""
+
+FOLDER_ID=$(./folderput -d "$DB_NAME" "$FOLDER_KEY")
 
 mongo --quiet $MONGO_HOST/$MONGO_DB --eval "db.$MONGO_COLLECTION_RESOURCE.update( { key:\"$RESOURCE_KEY\" }, { \$set: { key:\"$RESOURCE_KEY\", name: \"$RESOURCE_NAME\", folder_id: $FOLDER_ID } }, { upsert: true } )" >/dev/null
 
